# Generated by Django 3.2.9 on 2021-12-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Auth',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='ratingCount',
            field=models.IntegerField(default=0),
        ),
    ]
