# Generated by Django 3.2.9 on 2021-12-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_auto_20211209_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Publisher',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='YearOfPublication',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='imgBookL',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='imgBookM',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
