# Generated by Django 3.2.9 on 2021-12-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0007_auto_20211209_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='SOME STRING', max_length=14),
        ),
    ]
