# Generated by Django 3.2.9 on 2021-12-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0008_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=255, null=True),
        ),
    ]
