# Generated by Django 3.2.9 on 2021-12-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0009_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='contents',
            field=models.CharField(default='SOME STRING', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='overview',
            field=models.CharField(default='SOME STRING', max_length=255, null=True),
        ),
    ]
