# Generated by Django 3.2.9 on 2021-12-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0014_auto_20211209_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ratingCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
