# Generated by Django 3.2.9 on 2021-12-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0015_alter_book_ratingcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='average_rating',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='num_pages',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='text_reviews_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
